name: deploy:docs

on:
  push:
    branches: [master, 'ci/**']

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.DOCS_DEPLOY_AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
      - name: Deploy docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        run: aws --version
#        run: |
#          cd docs/
#          npm install
#          npm run publish

